# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubefix < Formula
  desc "KubeFix - AI-powered Kubernetes troubleshooting"
  homepage "https://rocketcitydefense.com"
  version "0.1.2"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RCEIG/kubefix-product/releases/download/v0.1.2/kubefix-darwin-amd64.tar.gz"
      sha256 "45944f7410954502b58193408dc2085c9a207d350b1994b2fbfcae2d3e4480b3"

      def install
        bin.install "kubefix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RCEIG/kubefix-product/releases/download/v0.1.2/kubefix-darwin-arm64.tar.gz"
      sha256 "bc9a990d8f95d95ba6daca927d9823c22762a7e278852df041b13fafb07c6db2"

      def install
        bin.install "kubefix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RCEIG/kubefix-product/releases/download/v0.1.2/kubefix-linux-amd64.tar.gz"
      sha256 "d74d57e8c744f03f8bf1faf6aec7ccdc340e162d96271d8855f571ed849bcc2f"
      def install
        bin.install "kubefix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RCEIG/kubefix-product/releases/download/v0.1.2/kubefix-linux-arm64.tar.gz"
      sha256 "70ba740589f10df374232f78e454d350d8f7cecc9ea5365455ec3c64efa16784"
      def install
        bin.install "kubefix"
      end
    end
  end
end
