# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pforge < Formula
  desc "PipelineForge CLI for local pipeline generation and validation"
  homepage "https://pipelineforge.dev"
  version "1.1.2"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RCEIG/PipelineForge-Product/releases/download/v1.1.2/pforge-darwin-amd64.tar.gz"
      sha256 "f5c77de7e1781c18243904701f9350186347a32fc9124ef335f343af5c203fdb"

      def install
        bin.install "pforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RCEIG/PipelineForge-Product/releases/download/v1.1.2/pforge-darwin-arm64.tar.gz"
      sha256 "c7f8d1e5b0b07629dc5856af01043f8f4f048ce031623b2e577922e98f09a53e"

      def install
        bin.install "pforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RCEIG/PipelineForge-Product/releases/download/v1.1.2/pforge-linux-amd64.tar.gz"
      sha256 "c0b696b7fa5f55455f7f4e2c7c9bed00563ac69260eb2ddcfee00c4a0e1c5f91"
      def install
        bin.install "pforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RCEIG/PipelineForge-Product/releases/download/v1.1.2/pforge-linux-arm64.tar.gz"
      sha256 "b51dff8c2472b84376f13bcf72eb639b7e5acc8295c205413cb23826721af034"
      def install
        bin.install "pforge"
      end
    end
  end
end
