# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pforge < Formula
  desc "PipelineForge CLI for local pipeline generation and validation"
  homepage "https://pipelineforge.dev"
  version "1.2.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RCEIG/PipelineForge-Product/releases/download/v1.2.1/pforge-darwin-amd64.tar.gz"
      sha256 "8284f2f4c8090c2d3f4943333f770a8118eebd436dad0a79e16f59705cd01d81"

      define_method(:install) do
        bin.install "pforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RCEIG/PipelineForge-Product/releases/download/v1.2.1/pforge-darwin-arm64.tar.gz"
      sha256 "9604e06ff4054f16c9f6ae2fd53fa151fd9d62380f77aa047cd2963a616f5ca2"

      define_method(:install) do
        bin.install "pforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RCEIG/PipelineForge-Product/releases/download/v1.2.1/pforge-linux-amd64.tar.gz"
      sha256 "5844863895b6b3f406f063f6a1010088d35839396ee27d9b4417104d791b74e5"
      define_method(:install) do
        bin.install "pforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RCEIG/PipelineForge-Product/releases/download/v1.2.1/pforge-linux-arm64.tar.gz"
      sha256 "b8632c3b69619751064eefcafc46fad7b6f9582a412a0cb4223cfde3f1f19b6a"
      define_method(:install) do
        bin.install "pforge"
      end
    end
  end
end
