# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pforge < Formula
  desc "PipelineForge CLI for local pipeline generation and validation"
  homepage "https://pipelineforge.dev"
  version "1.2.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RCEIG/PipelineForge-Product/releases/download/v1.2.0/pforge-darwin-amd64.tar.gz"
      sha256 "683222a38751234de1593dca9466a31434f2895a04b52c958c83cc7712e53a4f"

      define_method(:install) do
        bin.install "pforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RCEIG/PipelineForge-Product/releases/download/v1.2.0/pforge-darwin-arm64.tar.gz"
      sha256 "5754d604dca5e00cbe3a39c6a72e2245076e76b929631e8d1f8d8df8beaf2982"

      define_method(:install) do
        bin.install "pforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RCEIG/PipelineForge-Product/releases/download/v1.2.0/pforge-linux-amd64.tar.gz"
      sha256 "5760dbf5a9e1fc3a77158e318f06e55e33ebe696615c7c0c5ec5af93ae95ecdc"
      define_method(:install) do
        bin.install "pforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RCEIG/PipelineForge-Product/releases/download/v1.2.0/pforge-linux-arm64.tar.gz"
      sha256 "1430af5a697629a49c35e0a65e31ad7f6c2cda69426d49352f3709be6a9fe29c"
      define_method(:install) do
        bin.install "pforge"
      end
    end
  end
end
