# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pguard < Formula
  desc "PipelineGuard - Secure your CI/CD pipelines"
  homepage "https://getpguard.com"
  version "2.13.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RCEIG/PipelineGuard-Product/releases/download/v2.13.0/pguard-darwin-amd64.tar.gz"
      sha256 "d07bdca3a53e0cf9a6b442516d5043b9aefde5216c31cd83a145afda9a8e3e65"

      define_method(:install) do
        bin.install "pguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RCEIG/PipelineGuard-Product/releases/download/v2.13.0/pguard-darwin-arm64.tar.gz"
      sha256 "1eef44ca4611ac37864528ff35639d90776e83248aeed02d54c3f659c3d3ed51"

      define_method(:install) do
        bin.install "pguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RCEIG/PipelineGuard-Product/releases/download/v2.13.0/pguard-linux-amd64.tar.gz"
      sha256 "3e34df4ea7610902dc055b87a4910447bb1c44c469f4613ae8714e5f5ef8f2c9"
      define_method(:install) do
        bin.install "pguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RCEIG/PipelineGuard-Product/releases/download/v2.13.0/pguard-linux-arm64.tar.gz"
      sha256 "d827bbc6e688255267b05135f47c6146baf6a136421ec819aa5d084c89e307d0"
      define_method(:install) do
        bin.install "pguard"
      end
    end
  end
end
