# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pguard < Formula
  desc "PipelineGuard - Secure your CI/CD pipelines"
  homepage "https://getpguard.com"
  version "2.12.2"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RCEIG/PipelineGuard-Product/releases/download/v2.12.2/pguard-darwin-amd64.tar.gz"
      sha256 "6aed16edb19e357318d59db259c4db75335a3ceefcf773067b9b1a812ffeb281"

      define_method(:install) do
        bin.install "pguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RCEIG/PipelineGuard-Product/releases/download/v2.12.2/pguard-darwin-arm64.tar.gz"
      sha256 "c1f99a3da7fea79ea03e5d6b22b271f16c0cd45212dd4a51cd2d95492c756488"

      define_method(:install) do
        bin.install "pguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RCEIG/PipelineGuard-Product/releases/download/v2.12.2/pguard-linux-amd64.tar.gz"
      sha256 "12d571a26c7dfad5df28717b36ec46abeee54a03f24120914b20cd3c271c12c7"
      define_method(:install) do
        bin.install "pguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RCEIG/PipelineGuard-Product/releases/download/v2.12.2/pguard-linux-arm64.tar.gz"
      sha256 "bd7f75f8ae54d7fc44ed03e613569f583ba0121c1b05281f73d5186a939ad810"
      define_method(:install) do
        bin.install "pguard"
      end
    end
  end
end
