# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pforge < Formula
  desc "PipelineForge CLI for local pipeline generation and validation"
  homepage "https://pipelineforge.dev"
  version "1.4.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.pipelineforge.dev/1.4.0/pforge-darwin-amd64.tar.gz"
      sha256 "609b9f38ce972b61d7ced9b0b55f3f3f1bc543988c81e20fdaa573d1a66f8b3c"

      define_method(:install) do
        bin.install "pforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.pipelineforge.dev/1.4.0/pforge-darwin-arm64.tar.gz"
      sha256 "e7464e60f0d76c2e3d5fbb2ad1802eabe175fa1d0b1b37ba096103c908d59122"

      define_method(:install) do
        bin.install "pforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.pipelineforge.dev/1.4.0/pforge-linux-amd64.tar.gz"
      sha256 "33a457a5b41b7fb5305f1437703ea8f11dd9a3f37fe48761843abf3d78283bdd"
      define_method(:install) do
        bin.install "pforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.pipelineforge.dev/1.4.0/pforge-linux-arm64.tar.gz"
      sha256 "d213c80b55bda5c7c39afa33d3235849bb9f66a9a8c8e80d3907ad124d325f3f"
      define_method(:install) do
        bin.install "pforge"
      end
    end
  end
end
